# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 82
use_small_heuristics = "Default"
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true