global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'retailer-users'
    static_configs:
      - targets: ['users:8080']
    metrics_path: /metrics

  - job_name: 'retailer-catalog'
    static_configs:
      - targets: ['catalog:8080']
    metrics_path: /metrics

  - job_name: 'retailer-cart'
    static_configs:
      - targets: ['cart:8080']
    metrics_path: /metrics

  - job_name: 'retailer-orders'
    static_configs:
      - targets: ['orders:8080']
    metrics_path: /metrics

  - job_name: 'retailer-payments'
    static_configs:
      - targets: ['payments:8080']
    metrics_path: /metrics

  - job_name: 'retailer-notifications'
    static_configs:
      - targets: ['notifications:8080']
    metrics_path: /metrics